### ISSUE TITLE
Suggestion: Simplify CSS code as much as possible.

### ISSUE THREAD

**Issue by josephtkim** [sirusazadi/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. You did a great job simplifying the code for the font-family property, but it can be simplified further for other shared properties among the selectors. For instance, 

```css
html {
    font-family: Helvetica, sans-serif;
    font-weight: bold;
}

h2 {
    font-size: 32px;
    color: white;
}
```
